tasks:
  - name: Python environment
    command: |
      apt-get install python3-flask -y
      pip3 install -r requirements.txt
      python -m venv venv
      source ./venv/bin/activate
      export FLASK_APP=./app/vuln_app.py
      export FLASK_ENV=development
      flask --debug run
  - name: Local terminal
    init: git config --global gpg.format ssh && git config --global user.signingkey "$GP_SSH_SIGNING_KEY" && git config --global commit.gpgsign true
    command: bash

ports:
  - name: flask-app
    description: The flask web app 
    port: 5000
    visibility: private
    onOpen: open-preview
